name: build docker

on:
  push:
    branches:
      - main  # Set a branch that will trigger a deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5.8
        name: Build & push Docker image V1
        with:
          image: mohamadmokhtar/library
          tags: simple-http-server-v1
          registry: docker.io
          dockerfile: Dockerfile
          directory: V1
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: mr-smithers-excellent/docker-build-push@v5.8
        name: Build & push Docker image V2
        with:
          image: mohamadmokhtar/library
          tags: simple-http-server-v2
          registry: docker.io
          dockerfile: Dockerfile
          directory: V2
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: mr-smithers-excellent/docker-build-push@v5.8
        name: Build & push Docker image V3
        with:
          image: mohamadmokhtar/library
          tags: simple-http-server-v3
          registry: docker.io
          dockerfile: Dockerfile
          directory: V3
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: mr-smithers-excellent/docker-build-push@v5.8
        name: Build & push Docker image V4
        with:
          image: mohamadmokhtar/library
          tags: simple-http-server-v4
          registry: docker.io
          dockerfile: Dockerfile
          directory: V4
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
